SELECT YEAR(d1.DIFFERENTIATION_DATE) AS YEAR,
(SELECT MAX(SIZE_OF_COLONY) FROM ECOLI_DATA d2
WHERE YEAR(d1.DIFFERENTIATION_DATE) = YEAR(d2.DIFFERENTIATION_DATE)
GROUP BY YEAR(d2.DIFFERENTIATION_DATE))-d1.SIZE_OF_COLONY AS YEAR_DEV ,
d1.ID
FROM ECOLI_DATA d1
ORDER BY YEAR ASC,YEAR_DEV ASC

